### ISSUE TITLE
Can we make all options environment variables?

### ISSUE THREAD

**Issue by shawndwells** [CrowdStrike/container-image-scan-action#2]
Could the script be updated so that all options (eg clientID, cloud region, etc) be environment variables?

Or update the logic such as "if env var present, use it; else, check yaml" ?

**Comment by redhatrises** [comment]
Why do we need to make everything an environment variable?

**Comment by shawndwells** [comment]
Not need, more like an option.

Many people don't want their CIDs, ClientIDs, or cloud region information, exposed.

**Comment by redhatrises** [comment]
What do you think should be considered "protected information" besides the secret?

**Comment by shawndwells** [comment]
As an option, all of it

**Comment by redhatrises** [comment]
Okay, so you should be able to use the following (which is normal GH environment'isms):

```
        with:
          falcon_client_id: "${{ secrets.FALCON_CLIENT_ID }}"
          container_repository: docker.io/library/busybox
        env:
          FALCON_CLIENT_SECRET: "${{ secrets.FALCON_CLIENT_SECRET }}"
```

The reason that `FALCON_CLIENT_SECRET` is only an environment variable is to not cli arg the OAUTH secret.

However, looks like the information is displayed in the action output... so will need to update for env vars
